



INSERT INTO `states` (`id`, `name`, `abbreviation`, `created`, `modified`) VALUES
(1, 'Agrigento', 'AG', now(), now()),
(2, 'Alessandria', 'AL', now(), now()),
(3, 'Ancona', 'AN', now(), now()),
(4, 'Aosta', 'AO', now(), now()),
(5, 'Arezzo', 'AR', now(), now()),
(6, 'Ascoli Piceno', 'AP', now(), now()),
(7, 'Asti', 'AT', now(), now()),
(8, 'Avellino', 'AV', now(), now()),
(9, 'Bari', 'BA', now(), now()),
(10, 'Barletta-Andria-Trani', 'BT', now(), now()),
(11, 'Belluno', 'BL', now(), now()),
(12, 'Benevento', 'BN', now(), now()),
(13, 'Bergamo', 'BG', now(), now()),
(14, 'Biella', 'BI', now(), now()),
(15, 'Bologna', 'BO', now(), now()),
(16, 'Bolzano', 'BZ', now(), now()),
(17, 'Brescia', 'BS', now(), now()),
(18, 'Brindisi', 'BR', now(), now()),
(19, 'Cagliari', 'CA', now(), now()),
(20, 'Caltanissetta', 'CL', now(), now()),
(21, 'Campobasso', 'CB', now(), now()),
(22, 'Carbonia-Iglesias', 'CI', now(), now()),
(23, 'Caserta', 'CE', now(), now()),
(24, 'Catania', 'CT', now(), now()),
(25, 'Catanzaro', 'CZ', now(), now()),
(26, 'Chieti', 'CH', now(), now()),
(27, 'Como', 'CO', now(), now()),
(28, 'Cosenza', 'CS', now(), now()),
(29, 'Cremona', 'CR', now(), now()),
(30, 'Crotone', 'KR', now(), now()),
(31, 'Cuneo', 'CN', now(), now()),
(32, 'Enna', 'EN', now(), now()),
(33, 'Fermo', 'FM', now(), now()),
(34, 'Ferrara', 'FE', now(), now()),
(35, 'Firenze', 'FI', now(), now()),
(36, 'Foggia', 'FG', now(), now()),
(37, 'Forl?-Cesena', 'FC', now(), now()),
(38, 'Frosinone', 'FR', now(), now()),
(39, 'Genova', 'GE', now(), now()),
(40, 'Gorizia', 'GO', now(), now()),
(41, 'Grosseto', 'GR', now(), now()),
(42, 'Imperia', 'IM', now(), now()),
(43, 'Isernia', 'IS', now(), now()),
(44, 'La Spezia', 'SP', now(), now()),
(45, 'L\'Aquila', 'AQ', now(), now()),
(46, 'Latina', 'LT', now(), now()),
(47, 'Lecce', 'LE', now(), now()),
(48, 'Lecco', 'LC', now(), now()),
(49, 'Livorno', 'LI', now(), now()),
(50, 'Lodi', 'LO', now(), now()),
(51, 'Lucca', 'LU', now(), now()),
(52, 'Macerata', 'MC', now(), now()),
(53, 'Mantova', 'MN', now(), now()),
(54, 'Massa-Carrara', 'MS', now(), now()),
(55, 'Matera', 'MT', now(), now()),
(56, 'Messina', 'ME', now(), now()),
(57, 'Milano', 'MI', now(), now()),
(58, 'Modena', 'MO', now(), now()),
(59, 'Monza e della Brianza', 'MB', now(), now()),
(60, 'Napoli', 'NA', now(), now()),
(61, 'Novara', 'NO', now(), now()),
(62, 'Nuoro', 'NU', now(), now()),
(63, 'Olbia-Tempio', 'OT', now(), now()),
(64, 'Oristano', 'OR', now(), now()),
(65, 'Padova', 'PD', now(), now()),
(66, 'Palermo', 'PA', now(), now()),
(67, 'Parma', 'PR', now(), now()),
(68, 'Pavia', 'PV', now(), now()),
(69, 'Perugia', 'PG', now(), now()),
(70, 'Pesaro e Urbino', 'PU', now(), now()),
(71, 'Pescara', 'PE', now(), now()),
(72, 'Piacenza', 'PC', now(), now()),
(73, 'Pisa', 'PI', now(), now()),
(74, 'Pistoia', 'PT', now(), now()),
(75, 'Pordenone', 'PN', now(), now()),
(76, 'Potenza', 'PZ', now(), now()),
(77, 'Prato', 'PO', now(), now()),
(78, 'Ragusa', 'RG', now(), now()),
(79, 'Ravenna', 'RA', now(), now()),
(80, 'Reggio Calabria', 'RC', now(), now()),
(81, 'Reggio Emilia', 'RE', now(), now()),
(82, 'Rieti', 'RI', now(), now()),
(83, 'Rimini', 'RN', now(), now()),
(84, 'Roma', 'RM', now(), now()),
(85, 'Rovigo', 'RO', now(), now()),
(86, 'Salerno', 'SA', now(), now()),
(87, 'Medio Campidano', 'VS', now(), now()),
(88, 'Sassari', 'SS', now(), now()),
(89, 'Savona', 'SV', now(), now()),
(90, 'Siena', 'SI', now(), now()),
(91, 'Siracusa', 'SR', now(), now()),
(92, 'Sondrio', 'SO', now(), now()),
(93, 'Taranto', 'TA', now(), now()),
(94, 'Teramo', 'TE', now(), now()),
(95, 'Terni', 'TR', now(), now()),
(96, 'Torino', 'TO', now(), now()),
(97, 'Ogliastra', 'OG', now(), now()),
(98, 'Trapani', 'TP', now(), now()),
(99, 'Trento', 'TN', now(), now()),
(100, 'Treviso', 'TV', now(), now()),
(101, 'Trieste', 'TS', now(), now()),
(102, 'Udine', 'UD', now(), now()),
(103, 'Varese', 'VA', now(), now()),
(104, 'Venezia', 'VE', now(), now()),
(105, 'Verbano-Cusio-Ossola', 'VB', now(), now()),
(106, 'Vercelli', 'VC', now(), now()),
(107, 'Verona', 'VR', now(), now()),
(108, 'Vibo Valentia', 'VV', now(), now()),
(109, 'Vicenza', 'VI', now(), now()),
(110, 'Viterbo', 'VT', now(), now());
